version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bingsuCoinsTrans"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1goh4bv0a5re7"
s3_prefix = "bingsuCoinsTrans"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
